Repository Up-North-Coding/jovian, pull requests merged in 2022-06, with the labels that each got.

#42 Refactor JUPTable Component so it Builds its own Rows Generically
  src/components/JUPTable/JUPTable.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/BlocksWidget.tsx
  src/views/Dashboard/components/Widgets/TransactionsWidget/TransactionsWidget.tsx
Labels: ready2merge

#44 Improve JUPDialog Styling
  proxy/server.js
  src/App.tsx
  src/components/JUPDialog/JUPDialog.tsx
  src/components/JUPTable/JUPTable.tsx
  src/components/JUPTable/index.ts
  src/components/SearchBar/components/AddressBook/AddressBook.tsx
  src/utils/api/constants.ts
  src/views/Dashboard/components/Widgets/BlocksWidget/BlocksWidget.tsx
  src/views/Dashboard/components/Widgets/TransactionsWidget/TransactionsWidget.tsx
Labels: ready2merge

#35 Logout Functionality
  src/components/SearchBar/SearchBar.tsx
  src/contexts/AccountContext/Provider.tsx
  src/contexts/AccountContext/types.ts
Labels: ready2merge

#41 Mobile Styling for Dashboard
  proxy/server.js
  src/App.tsx
  src/components/Drawer/Drawer.tsx
  src/components/JUPAppBar/JUPAppBar.tsx
  src/components/JUPAppBar/index.ts
  src/components/JUPDialog/JUPDialog.tsx
  src/components/JUPSettingsMenu/JUPSettingsMenu.tsx
  src/components/JUPSettingsMenu/index.ts
  src/components/JUPTable/JUPTable.tsx
  src/components/JUPTable/index.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/components/AddressBook/AddressBook.tsx
  src/components/SearchBar/components/BlockheightChip/BlockheightChip.tsx
  src/contexts/AccountContext/Provider.tsx
  src/contexts/AccountContext/types.ts
  src/utils/api/constants.ts
  src/utils/common/constants.ts
  src/views/Dashboard/Dashboard.tsx
  src/views/Dashboard/components/WidgetContainer/WidgetContainer.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/BlocksWidget.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/AvgBlockTime/AvgBlockTimeDisplay.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/AvgBlockTime/index.ts
  src/views/Dashboard/components/Widgets/BlocksWidget/components/DailyTransactionsDisplay/DailyTransactionsDisplay.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/DailyTransactionsDisplay/index.ts
  src/views/Dashboard/components/Widgets/TransactionsWidget/TransactionsWidget.tsx
  src/views/Transactions/Transactions.tsx
Labels: enhancement, ready for review

#30 Recent Blocks Widget
  proxy/server.js
  src/App.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/components/UserInfo/UserInfo.tsx
  src/components/JUPAppBar/JUPAppBar.tsx
  src/components/JUPAppBar/index.ts
  src/components/JUPDialog/JUPDialog.tsx
  src/components/JUPSettingsMenu/JUPSettingsMenu.tsx
  src/components/JUPSettingsMenu/index.ts
  src/components/JUPTable/JUPTable.tsx
  src/components/JUPTable/index.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/components/AddressBook/AddressBook.tsx
  src/components/SearchBar/components/BlockheightChip/BlockheightChip.tsx
  src/contexts/APIContext/Provider.tsx
  src/contexts/APIContext/types.ts
  src/contexts/AccountContext/Provider.tsx
  src/contexts/BlockContext/Provider.tsx
  src/contexts/BlockContext/types.ts
  src/types/NXTAPI/index.ts
  src/utils/api/api.ts
  src/utils/api/constants.ts
  src/utils/api/getBlocks.ts
  src/utils/common/AvgBlockTime.ts
  src/utils/common/DailyTransactionCount.ts
  src/utils/common/constants.ts
  src/views/Dashboard/Dashboard.tsx
  src/views/Dashboard/components/WidgetContainer/WidgetContainer.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/BlocksWidget.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/AvgBlockTime/AvgBlockTimeDisplay.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/AvgBlockTime/index.ts
  src/views/Dashboard/components/Widgets/BlocksWidget/components/DailyTransactionsDisplay/DailyTransactionsDisplay.tsx
  src/views/Dashboard/components/Widgets/BlocksWidget/components/DailyTransactionsDisplay/index.ts
  src/views/Dashboard/components/Widgets/BlocksWidget/index.ts
  src/views/Dashboard/components/Widgets/TransactionsWidget/TransactionsWidget.tsx
  src/views/Transactions/Transactions.tsx
Labels: ready for review

#52 updated checking of data when using a juptable. now runtimer errors a…
  src/components/JUPTable/JUPTable.tsx
Labels: enhancement, ready for review

#56 refactor of sendwidget -> sendJup to APIRouterProvider
  src/App.tsx
  src/contexts/APIContext/Provider.tsx
  src/contexts/APIContext/types.ts
  src/contexts/APIRouterContext/Context.ts
  src/contexts/APIRouterContext/Provider.tsx
  src/contexts/APIRouterContext/index.ts
  src/contexts/APIRouterContext/types.ts
  src/hooks/useAPIRouter.ts
  src/views/Dashboard/components/Widgets/SendWidget/SendWidget.tsx
Labels: enhancement, ready for review
